# Generated by Django 3.2.5 on 2021-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210714_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.IntegerField()),
                ('textarea', models.TextField()),
            ],
        ),
    ]
